/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echoClient;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

public class EchoClient {

    public static void main(String[] args) {

        String ip = "localhost";
        int port = 7778;

        Socket mSocket;

        BufferedReader brRecv;				//Recv
        PrintWriter pwSend;					//Send
        BufferedReader brConsoleInput; 		//Console Input
        try {
            mSocket = new Socket(ip, port);// 소켓 생성후 서버 연결

            System.out.println("Connect Success");

            brRecv = new BufferedReader(new InputStreamReader(mSocket.getInputStream()));
            pwSend = new PrintWriter(mSocket.getOutputStream());
            brConsoleInput= new BufferedReader(new InputStreamReader(System.in));

            while (true) {
                String s = brConsoleInput.readLine();		//콘솔 입력
                pwSend.println(s);
                pwSend.flush();
                if (s.equals("exit")) {						//exit 입력시 종료
                    break;
                }
                System.out.println(brRecv.readLine());		//echo 메시지 수신
            }

            mSocket.close();	// 소켓 닫기 (연결 끊기)

        } catch (IOException e) {
            System.out.println(e.getMessage());
        }
    }

}
/*
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;

public class echoClient {
    public static void main(String[] args) throws Exception {

        Socket socket = new Socket("localhost", 11111);
        PrintWriter out = new PrintWriter(socket.getOutputStream());
        BufferedReader networkIn = new BufferedReader(new InputStreamReader(socket.getInputStream()));
        BufferedReader userIn = new BufferedReader(new InputStreamReader(System.in));
        System.out.println("클라이언트 입장");

        while (true) {
            System.out.print("입력하세요:");
            String theLine = userIn.readLine();
            out.println(theLine);
            out.flush();
            if (theLine.equalsIgnoreCase("Quit"))
                break;
            System.out.println("서버에서 보냄:[ " + networkIn.readLine() + " ]");
        }
        System.out.println("클라이언트 종료..");
        networkIn.close();
        out.close();
        socket.close();
    }
}
*/
