/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package echoClient;

import org.junit.Test;
import static org.junit.Assert.*;

public class EchoClientTest {
    @Test public void testAppHasAGreeting() {
        EchoClient classUnderTest = new EchoClient();
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
